// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytfuenxlejrogesnsvhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZnVlbnhsZWpyb2dlc25zdmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1NzM3MTIsImV4cCI6MjA1NTE0OTcxMn0.jVJkwzXK54_1zN7Xidl2wy0wPOdHZSlBhNvOaUI3iEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);